
image: mono

stages:
  - build

bdhero:
  stage: build
  script:
    - apt-get update -qq && apt-get install -qq powershell
    - nuget restore src/BDHero.sln
    - msbuild src/BDHero.sln /p:Configuration=Release
    - ls -l ./
    - ls -l ./artifacts
    - ls -l ./artifacts/Portable
  artifacts:
    paths:
      - ./packages/Portable
      
    