
os: windows
language: shell

script:
  - choco install nuget.commandline
  - nuget restore src/bdhero.sln
  - dotnet build src/bdhero.sln
  - ls -l
  - ls -l artifacts
  - ls -l artifacts/portable
  - ls -l artifacts/portable/plugins/required
  - ls -l artifacts/portable/plugins/required/ffmpegmuxer
